import { Check, Package } from "lucide-react";
import { DeliveryComplete } from "./delivery-complete";
import { orderProgress, type ProgressOrder } from "@/lib/orders/progress";
export function CustomerProgress({ order, deliveredAt }: { order: ProgressOrder; deliveredAt?: Date | null }) {
  if (order.orderStatus === "ENTREGADO") return <DeliveryComplete deliveredAt={deliveredAt} />;
  const progress = orderProgress(order);
  const steps = ["Pedido recibido", "Pago", "Preparación", order.deliveryType === "delivery" ? "Envío" : "Recojo", "Entrega"];
  return <section className="overflow-hidden rounded-2xl border border-border bg-white"><div className="flex gap-4 bg-secondary/40 p-5 sm:p-6"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-white text-primary"><Package className="size-5" /></span><div><p className="text-[10px] font-semibold uppercase tracking-wider text-primary">Así va tu pedido</p><h2 className="mt-2 text-xl font-semibold tracking-tight">{progress.title}</h2><p className="mt-2 text-xs leading-6 text-muted-foreground">{progress.description}</p></div></div>{progress.index >= 0 ? <ol className="grid grid-cols-5 gap-2 px-4 py-6 sm:px-6">{steps.map((step, index) => <li key={step} aria-current={index === progress.index ? "step" : undefined} className="text-center"><span className={`mx-auto flex size-8 items-center justify-center rounded-full border text-xs font-semibold ${index < progress.index || progress.index === 4 ? "border-primary bg-primary text-white" : index === progress.index ? "border-primary bg-secondary text-primary" : "border-border text-muted-foreground"}`}>{index < progress.index || progress.index === 4 ? <Check className="size-4" /> : index + 1}</span><p className={`mt-2 text-[10px] leading-4 sm:text-xs ${index <= progress.index ? "font-medium" : "text-muted-foreground"}`}>{step}</p></li>)}</ol> : null}</section>;
}
