"use client";
import { useState, useTransition } from "react";
import { Button } from "@/components/ui/button";
import { addTreasuryNoteAction, addObservationAction } from "@/app/tesoreria-recaudacion/operations";
import { noteSchema, observationSchema } from "@/lib/treasury/validation";
export function TreasuryComposer({ id, version, note = false }: { id: string; version: string; note?: boolean }) {
  const [content, setContent] = useState(""); const [category, setCategory] = useState<"datos" | "importes" | "comprobantes">("datos"); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  return <form noValidate data-order-editing={pending || content ? "true" : undefined} onSubmit={(e) => { e.preventDefault(); const input = { id, version, content, category }; const parsed = note ? noteSchema.safeParse(input) : observationSchema.safeParse(input); if (!parsed.success) { setError(parsed.error.issues[0].message); return; } startTransition(async () => { try { const result = note ? await addTreasuryNoteAction(input) : await addObservationAction(input); if (result.success) { setContent(""); setError(""); } else setError(result.message); } catch { setError("No se pudo registrar. Reintenta."); } }); }} className="space-y-3">{!note ? <label className="block text-xs font-medium">Tipo de observación<select value={category} disabled={pending} onChange={(e) => setCategory(e.target.value as typeof category)} className="mt-2 h-10 w-full cursor-pointer rounded-lg border border-input bg-white px-3"><option value="datos">Datos de emisión</option><option value="importes">Importes</option><option value="comprobantes">Comprobantes de pago</option></select></label> : null}<label className="block text-xs font-medium">{note ? "Nota privada para el equipo" : "Corrección solicitada a Fondo Editorial"}<textarea value={content} onChange={(e) => setContent(e.target.value)} disabled={pending} maxLength={2000} placeholder={note ? "Añade un comentario para tu equipo…" : "Describe los datos o documentos que se deben corregir…"} className="mt-2 min-h-24 w-full rounded-lg border border-input p-3 text-sm" /></label><Button disabled={pending || !content.trim()} className="cursor-pointer" size="sm" type="submit">{pending ? "Guardando…" : note ? "Añadir nota" : "Registrar observación"}</Button>{error ? <p role="alert" className="text-xs text-destructive">{error}</p> : null}</form>;
}
