"use client";
import dynamic from "next/dynamic";
import { useState, useTransition } from "react";
import { Button } from "@/components/ui/button";
import { resolveObservationAction } from "@/app/tesoreria-recaudacion/operations";
import { resolveSchema } from "@/lib/treasury/validation";
const SupportingPond = dynamic(() => import("./supporting-pond"), { ssr: false });
type Correction = { name: string; document: string; phone: string; billingRuc: string; billingBusinessName: string; billingAddress: string };
export function ResolveTreasuryObservation({ id, observationId, category, current }: { id: string; observationId: string; category: string; current: Correction }) {
  const [response, setResponse] = useState(""); const [correction, setCorrection] = useState(current); const [edit, setEdit] = useState(false); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  return <form noValidate className="mt-3 space-y-3" data-order-editing={response || edit ? "true" : undefined} onSubmit={(e) => { e.preventDefault(); if (document.querySelector('[data-treasury-upload-busy="true"]')) { setError("Espera a que termine la carga."); return; } const input = { id, observationId, response, ...(edit ? { correction } : {}) }; const parsed = resolveSchema.safeParse(input); if (!parsed.success) { setError(parsed.error.issues[0].message); return; } startTransition(async () => { try { const result = await resolveObservationAction(parsed.data); if (!result.success) setError(result.message); } catch { setError("No se pudo registrar la subsanación."); } }); }}><label className="block text-xs font-medium">Respuesta de Fondo Editorial<textarea value={response} onChange={(e) => setResponse(e.target.value)} maxLength={2000} placeholder="Describe la corrección, coordinación o regularización realizada" className="mt-2 min-h-20 w-full rounded-lg border border-input p-3 text-xs" /></label><label className="flex cursor-pointer items-center gap-2 text-xs"><input type="checkbox" checked={edit} onChange={(e) => setEdit(e.target.checked)} />Actualizar los datos para emitir el documento</label>{edit ? <div className="grid gap-3 sm:grid-cols-2">{([{ key: "name", label: "Nombre", placeholder: "Nombres y apellidos" }, { key: "document", label: "Documento", placeholder: "DNI / CE" }, { key: "phone", label: "Celular", placeholder: "987654321" }, { key: "billingRuc", label: "RUC (vacío para boleta)", placeholder: "11 dígitos" }, { key: "billingBusinessName", label: "Razón social", placeholder: "Nombre de la empresa" }, { key: "billingAddress", label: "Dirección fiscal", placeholder: "Dirección completa para facturar" }] as const).map((field) => <label key={field.key} className="text-xs">{field.label}<input value={correction[field.key]} onChange={(e) => setCorrection({ ...correction, [field.key]: e.target.value })} placeholder={field.placeholder} maxLength={field.key === "billingAddress" ? 500 : field.key === "billingRuc" ? 11 : field.key === "phone" ? 24 : field.key === "document" ? 20 : 160} className="mt-1 h-10 w-full rounded-lg border border-input px-3 text-xs" /></label>)}</div> : null}{category === "importes" ? <p className="text-[10px] leading-5 text-muted-foreground">Los importes originales y pagos verificados se conservan. Registra aquí la regularización acordada.</p> : null}<Button type="submit" disabled={pending || response.trim().length < 5} size="sm">Resolver observación</Button>{error ? <p role="alert" className="text-xs text-destructive">{error}</p> : null}</form>;
}
export function TreasurySupportingUpload({ id }: { id: string }) { return <div className="mt-4"><h4 className="mb-3 text-xs font-semibold">Añadir documentos de subsanación</h4><SupportingPond id={id} /></div>; }
