import { SortableTable } from "@/components/sortable-table";
import Link from "next/link";
import { BarChart3, Banknote, Package, CheckCheck, Clock3, UsersRound, AlertCircle } from "lucide-react";
import { requirePageAccess } from "@/lib/access";
import { getDashboard, dashboardManagers } from "@/lib/dashboard/data";
import { dashboardFiltersSchema, dashboardTabSchema, peruToday } from "@/lib/dashboard/validation";
import type { DurationMetric } from "@/lib/dashboard/types";
import { formatMoney } from "@/lib/orders/money";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { TrendChart, StockRanking } from "@/components/dashboard/charts";
import { OrderLiveRefresh } from "@/components/order-live-refresh";
import { Button } from "@/components/ui/button";
export const metadata = { title: "Dashboard", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
const number = new Intl.NumberFormat("es-PE");
function duration(metric: DurationMetric) {
  if (metric.hours === null || !metric.sample) return "Sin datos";
  return metric.hours < 24 ? `${number.format(Math.round(metric.hours * 10) / 10)} h` : `${number.format(Math.round(metric.hours / 24 * 10) / 10)} días`;
}
const fieldClass = "h-10 w-full rounded-lg border border-border bg-white px-3 text-sm focus-visible:outline-primary";
export default async function DashboardPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requirePageAccess();
  const today = peruToday();
  const schema = dashboardFiltersSchema(today);
  const query = await searchParams;
  const tab = dashboardTabSchema.parse(query.tab);
  const parsed = schema.safeParse(query);
  const filters = parsed.success ? parsed.data : schema.parse({});
  const [data, managers] = await Promise.all([getDashboard(filters), tab === "inventario" ? Promise.resolve([]) : dashboardManagers()]);
  const tabs = [{ value: "pedidos", label: "Pedidos e importes" }, { value: "atencion", label: "Atención" }, { value: "inventario", label: "Inventario" }] as const;
  function tabHref(value: string) {
    return `/admin/dashboard?${new URLSearchParams({ ...filters, tab: value }).toString()}`;
  }
  const { period, live, stock, times } = data;
  const metrics = [
    { title: "Pedidos registrados", value: number.format(period.count), detail: "Incluye cancelados", Icon: BarChart3 },
    { title: "Importe solicitado", value: formatMoney(period.requestedCents), detail: "Pedidos vigentes · incluye envío", Icon: Banknote },
    { title: "Pago verificado", value: formatMoney(period.verifiedCents), detail: "Solo sellos con pago aprobado", Icon: CheckCheck },
    { title: "Pedidos entregados", value: number.format(period.delivered), detail: `${formatMoney(period.deliveredCents)} · ${period.count ? Math.round(period.delivered / period.count * 100) : 0}% del período`, Icon: Package },
  ];
  const states = [{ title: "Esperando pago", value: live.waiting }, { title: "En revisión", value: live.review }, { title: "En distribución", value: live.distribution }, { title: "Despachados / listos para recojo", value: live.dispatched }];
  return <div className="space-y-7">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-primary">Resumen operativo</p><h1 className="page-heading mt-2">Dashboard</h1><p className="mt-3 text-sm text-muted-foreground">Consulta cada área desde su pestaña.</p></div><div className="flex items-center gap-3"><span className="text-right text-[10px] leading-5 text-muted-foreground">Actualizado<br />{new Intl.DateTimeFormat("es-PE", { timeZone: "America/Lima", dateStyle: "short", timeStyle: "short" }).format(new Date(data.asOf))}</span><OrderLiveRefresh finished /></div></header>
    <nav aria-label="Secciones del dashboard" className="flex gap-1 overflow-x-auto border-b border-border">
      {tabs.map((item) => <Link key={item.value} id={`dashboard-${item.value}`} href={tabHref(item.value)} scroll={false} prefetch={false} aria-current={tab === item.value ? "page" : undefined} className={`inline-flex min-h-11 shrink-0 items-center border-b-2 px-4 text-sm font-medium transition-colors focus-visible:outline-primary ${tab === item.value ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}>{item.label}</Link>)}
    </nav>
    <form action="/admin/dashboard" className={`grid items-end gap-3 rounded-xl border border-border bg-muted/20 p-4 ${tab === "inventario" ? "sm:grid-cols-[minmax(0,20rem)_auto] sm:justify-start" : "sm:grid-cols-2 lg:grid-cols-[1fr_1fr_1fr_1.3fr_auto]"}`}>
      <input type="hidden" name="tab" value={tab} />
      {tab !== "inventario" ? <>
      <label className="space-y-2 text-xs font-medium">Desde<input name="from" type="date" required defaultValue={filters.from} className={fieldClass} /></label>
      <label className="space-y-2 text-xs font-medium">Hasta<input name="to" type="date" required defaultValue={filters.to} className={fieldClass} /></label>
      </> : <><input type="hidden" name="from" value={filters.from} /><input type="hidden" name="to" value={filters.to} /></>}
      <label className="space-y-2 text-xs font-medium">Sello editorial<select name="imprint" defaultValue={filters.imprint} className={`${fieldClass} cursor-pointer`}><option value="">Ambos sellos</option><option value="universidad">Universidad</option><option value="instituto">Instituto</option></select></label>
      {tab !== "inventario" ? <label className="space-y-2 text-xs font-medium">Gestor<select name="manager" defaultValue={filters.manager} className={`${fieldClass} cursor-pointer`}><option value="">Todo el equipo</option>{managers.map((manager) => <option key={manager.id} value={manager.email}>{manager.email}</option>)}</select></label> : <input type="hidden" name="manager" value={filters.manager} />}
      <Button type="submit" className="h-10 cursor-pointer">Aplicar</Button>
    </form>
    {!parsed.success ? <p role="alert" className="text-sm text-destructive">{parsed.error.issues[0]?.message} Mostramos el mes actual.</p> : null}
    <section id="dashboard-panel" aria-labelledby={`dashboard-${tab}`} className="space-y-7">
      {tab === "pedidos" ? <>
        <section aria-label="Indicadores del período"><div className="mb-4 flex flex-wrap justify-between gap-2"><h2 className="text-sm font-semibold">Pedidos registrados en el período</h2><span className="text-xs text-muted-foreground">Estados actuales · fechas en horario de Perú</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ title, value, detail, Icon }) => <Card key={title} className="gap-4 bg-white"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-xs font-medium text-muted-foreground">{title}</CardTitle><Icon className="size-4 text-primary" aria-hidden="true" /></CardHeader><CardContent><p className="text-2xl font-semibold tracking-tight tabular-nums">{value}</p><p className="mt-2 text-[11px] leading-5 text-muted-foreground">{detail}</p></CardContent></Card>)}</div><p className="mt-3 text-xs text-muted-foreground">Cancelados: {period.cancelled} ({period.count ? Math.round(period.cancelled / period.count * 100) : 0}%). Importes verificados excluyen cancelados; no representan conciliación bancaria ni devoluciones.</p></section>
    <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Evolución de pedidos</CardTitle><CardDescription>Por fecha de registro.</CardDescription></CardHeader><CardContent><TrendChart trend={data.trend} /><details className="mt-3 text-xs"><summary className="cursor-pointer text-primary">Consultar datos de la gráfica</summary><div className="mt-3 max-h-48 overflow-auto"><SortableTable className="w-full text-left"><caption className="sr-only">Pedidos e importes diarios</caption><thead><tr><th>Fecha</th><th>Pedidos</th><th>Solicitado</th><th>Verificado</th></tr></thead><tbody>{data.trend.map((row) => <tr key={row.day} className="border-b border-border"><td data-sort-value={row.day} className="py-2">{row.day}</td><td>{row.count}</td><td>{formatMoney(row.requestedCents)}</td><td>{formatMoney(row.verifiedCents)}</td></tr>)}</tbody></SortableTable></div></details></CardContent></Card><Card><CardHeader><CardTitle>Importes del período</CardTitle><CardDescription>Solicitado en morado; verificado en línea discontinua.</CardDescription></CardHeader><CardContent><TrendChart trend={data.trend} money /></CardContent></Card></div>
        <Card><CardHeader><CardTitle>Publicaciones más solicitadas</CardTitle><CardDescription>Pedidos vigentes del período · por unidades.</CardDescription></CardHeader><CardContent><StockRanking books={data.topBooks} /><ol className="mt-4 divide-y divide-border">{data.topBooks.map((book, i) => <li key={book.id} className="flex items-start justify-between gap-3 py-3 text-xs"><span className="leading-5">{i + 1}. {book.title}</span><span className="shrink-0 text-right font-medium">{book.quantity} unidades<br /><span className="font-normal text-muted-foreground">{formatMoney(book.cents)}</span></span></li>)}</ol></CardContent></Card>
      </> : tab === "atencion" ? <>
        <section className="rounded-xl border border-primary/15 bg-secondary/30 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="flex items-center gap-2 text-sm font-semibold"><UsersRound className="size-4 text-primary" />Situación actual</h2><Link href="/admin/pedidos" className="text-xs font-medium text-primary underline">Ir a pedidos</Link></div><p className="mt-2 text-xs text-muted-foreground">Todos los pedidos abiertos, sin límite de fechas. Respeta sello y gestor seleccionados.</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{states.map((state) => <div key={state.title}><p className="text-2xl font-semibold tabular-nums">{state.value}</p><p className="mt-1 text-xs text-muted-foreground">{state.title}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-5 border-t border-primary/10 pt-4 text-xs"><span>Sin asignar: <strong>{live.unassigned}</strong></span><span>Emisiones pendientes de Tesorería Recaudación: <strong>{live.cashPending}</strong> · incluye pedidos entregados</span></div><p className="mt-2 text-[10px] text-muted-foreground">Sin asignar y solicitudes de Tesorería Recaudación son indicadores adicionales; no se suman a los estados.</p></section>
    <section><h2 className="mb-4 flex items-center gap-2 text-sm font-semibold"><Clock3 className="size-4 text-primary" />Tiempos de atención</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{([{ label: "Primera asignación", metric: times.assignment }, { label: "Hasta despacho", metric: times.dispatch }, { label: "Hasta entrega", metric: times.delivery }, { label: "Emisión de documentos", metric: times.emission }]).map(({ label, metric }) => <Card key={label}><CardContent><p className="text-xs text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-semibold tabular-nums">{duration(metric)}</p><p className="mt-2 text-[11px] text-muted-foreground">Mediana · {metric.sample} {label === "Emisión de documentos" ? "solicitudes" : "pedidos"}</p></CardContent></Card>)}</div><p className="mt-3 text-xs text-muted-foreground">Desde el registro del pedido; emisión desde la solicitud a Tesorería Recaudación. Horas y días calendario, incluyendo la espera del comprador.</p></section>
        <Card><CardHeader><CardTitle>Atención por gestor</CardTitle><CardDescription>Registrados y entregados: período seleccionado. Abiertos: situación actual. Responsable actual o conservado al cierre, sin contabilizar notas como atención.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><SortableTable className="w-full min-w-[420px] text-left text-xs"><caption className="sr-only">Distribución de pedidos por responsable</caption><thead className="border-b border-border text-muted-foreground"><tr><th className="py-3 font-medium">Gestor</th><th className="text-right font-medium">Registrados</th><th className="text-right font-medium">Entregados</th><th className="text-right font-medium">Abiertos ahora</th></tr></thead><tbody>{data.managers.map((manager) => <tr key={manager.id ?? "unassigned"} className="border-b border-border"><th className="py-4 font-medium">{manager.name}</th><td className="text-right">{manager.count}</td><td className="text-right">{manager.delivered}</td><td className="text-right">{manager.open}</td></tr>)}</tbody></SortableTable></div>{!data.managers.length ? <p className="py-8 text-center text-sm text-muted-foreground">Sin pedidos para los filtros seleccionados.</p> : null}<p className="mt-4 text-xs text-muted-foreground">Tesorería Recaudación en pedidos del período: {data.cash.completed} solicitudes finalizadas y {data.cash.pending} pendientes.</p></CardContent></Card>
      </> : <>
        <Card><CardHeader><CardTitle>Stock actual</CardTitle><CardDescription>Catálogo activo del sello seleccionado. Independiente de fechas y gestor.</CardDescription></CardHeader><CardContent><div className="grid grid-cols-3 gap-3"><div><p className="text-2xl font-semibold">{number.format(stock.units)}</p><p className="mt-1 text-xs text-muted-foreground">Unidades</p></div><div><p className="text-2xl font-semibold">{stock.exhausted}</p><p className="mt-1 text-xs text-muted-foreground">Agotados</p></div><div><p className="text-2xl font-semibold">{stock.low}</p><p className="mt-1 text-xs text-muted-foreground">Stock bajo</p></div></div><p className="mt-4 text-xs text-muted-foreground">{stock.titles} títulos activos · stock bajo: de 1 a 5 unidades.</p><ul className="mt-4 divide-y divide-border">{stock.alerts.map((book) => <li key={book.id} className="flex items-start justify-between gap-3 py-3 text-xs"><span className="leading-5">{book.title}</span><span className={`shrink-0 rounded-md px-2 py-1 font-medium ${book.stock === 0 ? "bg-destructive/10 text-destructive" : "bg-secondary text-primary"}`}>{book.stock === 0 ? "Agotado" : `${book.stock} disponibles`}</span></li>)}</ul>{!stock.alerts.length ? <p className="mt-8 flex items-center gap-2 text-sm text-muted-foreground"><AlertCircle className="size-4" />{stock.titles ? "Sin títulos con stock bajo." : "Aún no hay publicaciones activas."}</p> : null}<Link href="/admin/inventario" className="mt-5 inline-block text-xs font-medium text-primary underline">Gestionar inventario</Link></CardContent></Card>
      </>}
    </section>
  </div>;
}
