import { formatMoney, toCents } from "./money";
import { imprintNames } from "./types";
import type { getTrackedOrder } from "./tracking";
import type { BankAccount } from "@/lib/payments/config";

export type EmailOrder = NonNullable<Awaited<ReturnType<typeof getTrackedOrder>>>;
export function escapeHtml(value: string) { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!); }
const money = (value: string) => escapeHtml(formatMoney(toCents(value)));
const cell = "padding:10px 0;border-bottom:1px solid #eeeeF3;font-size:13px;line-height:1.6";
const section = (title: string, content: string) => `<h2 style="margin:28px 0 12px;color:#6802c1;font-size:11px;letter-spacing:1.1px;text-transform:uppercase">${title}</h2>${content}`;
const row = (label: string, value: string) => `<tr><td style="${cell};color:#727280;width:38%;vertical-align:top">${label}</td><td style="${cell};color:#191922">${value}</td></tr>`;
const table = (content: string) => `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse">${content}</table>`;
export const emailSubject = (number: string) => `Pedido ${number} · Fondo Editorial`;

export function renderOrderEmail(tracking: EmailOrder, { intro, link, banks, notice }: {
  intro: string; link: string; banks?: { universidad: BankAccount[]; instituto: BankAccount[] };
  notice?: { title: string; body: string };
}) {
  const { order, items } = tracking;
  const date = new Intl.DateTimeFormat("es-PE", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Lima" }).format(order.createdAt);
  const buyer = table(row("Correo", escapeHtml(order.customerEmail)) + row("Teléfono", escapeHtml(order.customerPhone)) + row("Documento", escapeHtml(order.customerDocument)) + row("Tipo de cliente", order.customerType === "comunidad_continental" ? "Comunidad Continental" : "Público general") + (order.billingRuc ? row("RUC", escapeHtml(order.billingRuc)) + row("Razón social", escapeHtml(order.billingBusinessName ?? "")) : ""));
  const publications = `<table width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;font-size:12px"><thead><tr style="background:#f7f5fb;color:#727280"><th scope="col" style="padding:10px 12px;text-align:left;font-weight:500">Publicación</th><th scope="col" style="padding:10px;text-align:center;font-weight:500">Cant.</th><th scope="col" style="padding:10px 12px;text-align:right;font-weight:500">Subtotal</th></tr></thead><tbody>${items.map((item) => `<tr><td style="${cell};padding-left:12px">${escapeHtml(item.title)}<span style="display:block;color:${item.publisherImprint === "instituto" ? "#e4000b" : "#6802c1"};font-size:10px;margin-top:3px">${imprintNames[item.publisherImprint]}</span></td><td style="${cell};text-align:center">${item.quantity}</td><td style="${cell};padding-right:12px;text-align:right;white-space:nowrap">${money(item.subtotal)}</td></tr>`).join("")}</tbody></table>` + table(row("Publicaciones", formatMoney(toCents(order.subtotalUniversidad) + toCents(order.subtotalInstituto))) + row("Costo por envío", money(order.shippingCost))) + `<div style="margin-top:12px;background:#f3ecfb;border-radius:6px;padding:16px">${table(`<tr><td style="font-size:14px;font-weight:600">Total del pedido</td><td align="right" style="font-size:20px;font-weight:700;color:#6802c1">${money(order.total)}</td></tr>`)}</div>`;
  const bankContent = banks ? (["universidad", "instituto"] as const).filter((imprint) => (imprint === "universidad" ? order.paymentStatusUniversidad : order.paymentStatusInstituto) !== "NO_APLICA").map((imprint) => `<div style="margin:12px 0;border:1px solid #e9e5ef;border-radius:8px;padding:16px"><div style="color:${imprint === "instituto" ? "#e4000b" : "#6802c1"};font-size:12px;font-weight:700">${imprintNames[imprint]}</div><div style="margin:6px 0 12px;font-size:18px;font-weight:700">${money(imprint === "universidad" ? order.totalUniversidad : order.totalInstituto)}</div>${banks[imprint].map((account) => `<p style="margin:12px 0 4px;font-size:12px;font-weight:700">${escapeHtml(account.bank)} · Soles</p><p style="margin:0;color:#666674;font-size:11px;line-height:1.8">${escapeHtml(account.holder)}<br>Cuenta: <strong style="color:#191922">${escapeHtml(account.account)}</strong><br>CCI: <strong style="color:#191922">${escapeHtml(account.cci)}</strong></p>`).join("")}</div>`).join("") : "";
  const mixedNotice = banks && order.orderType === "mixto" ? `<div style="margin-top:22px;padding:16px;background:#fff9e9;border:1px solid #f4d275;border-radius:8px;font-size:12px;line-height:1.7"><strong style="color:#815a00">Dos sellos editoriales, dos depósitos independientes</strong><br>Deposita el importe de cada sello en una de sus cuentas. El costo por envío se incluye únicamente en Universidad Continental.</div>` : "";
  const update = notice ? `<div style="margin:20px 0;padding:16px;background:#f5effc;border-left:3px solid #6802c1;border-radius:4px;font-size:13px;line-height:1.7"><strong>${escapeHtml(notice.title)}</strong><p style="margin:6px 0 0">${escapeHtml(notice.body)}</p></div>` : "";
  const delivery = `<p style="margin:0;font-size:13px;font-weight:600">${order.deliveryType === "delivery" ? "Envío a domicilio" : "Recojo en biblioteca"}</p><p style="margin:8px 0 0;font-size:12px;line-height:1.8">${escapeHtml(order.deliveryAddress)}${order.deliveryDistrict ? `<br>${escapeHtml([order.deliveryDistrict, order.deliveryProvince, order.deliveryDepartment].filter(Boolean).join(", "))}` : ""}${order.deliveryReference ? `<br>Referencia: ${escapeHtml(order.deliveryReference)}` : ""}</p><p style="margin:10px 0 0;font-size:12px;line-height:1.8">${order.deliveryType === "delivery" ? "Recibe" : "Recoge"}: <strong>${escapeHtml(order.deliveryRecipient)}</strong>${order.deliveryRecipientPhone ? `<br>Teléfono: ${escapeHtml(order.deliveryRecipientPhone)}` : ""}</p>`;
  return `<!doctype html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pedido ${escapeHtml(order.orderNumber)}</title></head><body style="margin:0;background:#f4f2f7;color:#191922;font-family:Inter,Arial,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f2f7"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;background:#fff;border-radius:12px;overflow:hidden"><tr><td style="padding:26px 28px;font-size:19px;font-weight:700;letter-spacing:-.4px">Fondo Editorial</td></tr><tr><td style="padding:14px 28px;background:#6802c1;color:#fff">${table(`<tr><td style="color:#fff;font-size:13px;font-weight:700">Pedido N.° ${escapeHtml(order.orderNumber)}</td><td align="right" style="color:#f1e3ff;font-size:10px">${escapeHtml(date)}</td></tr>`)}</td></tr><tr><td style="padding:24px 28px 28px"><p style="margin:0;font-size:14px;line-height:1.8">Hola, <strong>${escapeHtml(order.customerName)}</strong>.</p><p style="margin:12px 0 0;color:#666674;font-size:12px;line-height:1.8">${escapeHtml(intro)}</p>${update}${section("Datos del comprador", buyer)}${mixedNotice}${section("Publicaciones solicitadas", publications)}${bankContent ? section("Datos para el pago", `<p style="font-size:12px;color:#666674;line-height:1.8">Elige una cuenta por sello. La guía de pago acompaña este correo.</p>${bankContent}`) : ""}${section("Datos para la entrega", delivery)}<p style="margin:28px 0 12px;text-align:center"><a href="${escapeHtml(link)}" style="display:inline-block;padding:13px 22px;border-radius:6px;background:#6802c1;color:#fff;font-size:12px;font-weight:600;text-decoration:none">Consultar mi pedido</a></p><p style="margin:0;color:#727280;font-size:11px;line-height:1.8;text-align:center">Consulta el estado y adjunta tus comprobantes desde este enlace.</p></td></tr><tr><td style="padding:16px 24px;background:#6802c1;color:#efe3ff;font-size:10px;line-height:1.8;text-align:center">Fondo Editorial · Universidad Continental</td></tr></table></td></tr></table></body></html>`;
}

export function renderOrderUpdate(tracking: EmailOrder, { title, body, link, trackingUrl }: { title: string; body: string; link: string; trackingUrl?: string }) {
  const safeTracking = trackingUrl && /^https:\/\//.test(trackingUrl) ? trackingUrl : null;
  return `<!doctype html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f4f2f7;font-family:Inter,Arial,sans-serif;color:#191922"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:560px;background:white;border-radius:12px;overflow:hidden"><tr><td style="padding:20px 26px;background:#6802c1;color:white;font-size:13px;font-weight:700">Fondo Editorial · Pedido ${escapeHtml(tracking.order.orderNumber)}</td></tr><tr><td style="padding:28px 26px"><p style="font-size:13px;margin:0">Hola, <strong>${escapeHtml(tracking.order.customerName)}</strong>.</p><h1 style="font-size:21px;line-height:1.4;margin:20px 0 12px">${escapeHtml(title)}</h1><p style="font-size:13px;line-height:1.9;color:#666674;margin:0">${escapeHtml(body)}</p>${safeTracking ? `<p style="margin:18px 0"><a href="${escapeHtml(safeTracking)}" style="color:#6802c1;font-size:12px">Consultar el envío con el courier</a></p>` : ""}<p style="margin:24px 0 0"><a href="${escapeHtml(link)}" style="display:inline-block;background:#6802c1;color:white;border-radius:6px;padding:13px 20px;text-decoration:none;font-size:12px;font-weight:600">Ver el estado de mi pedido</a></p><p style="font-size:10px;color:#727280;line-height:1.7;margin:24px 0 0">Esta actualización forma parte del pedido ${escapeHtml(tracking.order.orderNumber)}. Conserva este hilo para consultar sus avances.</p></td></tr></table></td></tr></table></body></html>`;
}
