import { formatMoney, toCents } from "./money";
import { imprintNames } from "./types";
import type { getTrackedOrder } from "./tracking";
export type EmailOrder = NonNullable<Awaited<ReturnType<typeof getTrackedOrder>>>;
export function escapeHtml(value: string) { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!); }
export const emailSubject = (number: string) => `Pedido ${number} · Fondo Editorial`;
const dateFormat = new Intl.DateTimeFormat("es-PE", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Lima" });
function shell(content: string) {
  return `<!doctype html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f4f2f7;font-family:Inter,Arial,sans-serif;color:#191922"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:560px;background:white;border-radius:12px;overflow:hidden"><tr><td style="padding:28px">${content}</td></tr></table></td></tr></table></body></html>`;
}
function action(link: string, label: string) {
  return `<table role="presentation" cellspacing="0" cellpadding="0" style="margin:18px 0 24px"><tr><td style="border-radius:7px;background:#6802c1"><a href="${escapeHtml(link)}" style="display:inline-block;padding:14px 20px;color:white;font-size:13px;font-weight:600;text-decoration:none">${escapeHtml(label)}</a></td></tr></table>`;
}
export function renderOrderEmail(tracking: EmailOrder, { intro, link }: { intro: string; link: string }) {
  const { order } = tracking;
  const applicable = (["universidad", "instituto"] as const).filter((imprint) => (imprint === "universidad" ? order.paymentStatusUniversidad : order.paymentStatusInstituto) !== "NO_APLICA");
  const amounts = applicable.map((imprint) => `<tr><td style="padding:16px;border-bottom:1px solid #ede9f4;color:${imprint === "instituto" ? "#e4000b" : "#6802c1"};font-size:12px;font-weight:600">${imprintNames[imprint]}</td><td align="right" style="padding:16px;border-bottom:1px solid #ede9f4;font-size:20px;font-weight:700;white-space:nowrap">${escapeHtml(formatMoney(toCents(imprint === "universidad" ? order.totalUniversidad : order.totalInstituto)))}</td></tr>`).join("");
  return shell(`<p style="margin:0;font-size:10px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#6802c1">Solicitud recibida · ${escapeHtml(dateFormat.format(order.createdAt))}</p><h1 style="margin:12px 0 0;font-size:25px;line-height:1.4">Registramos tu pedido ${escapeHtml(order.orderNumber)}</h1><p style="margin:16px 0 0;font-size:13px;line-height:1.9">Hola, <strong>${escapeHtml(order.customerName)}</strong>. ${escapeHtml(intro)}</p><h2 style="margin:24px 0 10px;font-size:13px">${order.orderType === "mixto" ? "Importes por sello editorial" : "Importe a depositar"}</h2><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#faf8fd;border:1px solid #ede9f4;border-radius:8px">${amounts}</table>${order.orderType === "mixto" ? `<p style="margin:14px 0 0;padding:14px;border-radius:7px;background:#fff9e9;font-size:12px;line-height:1.8">Realiza <strong>dos depósitos independientes</strong>, uno para cada sello.${toCents(order.shippingCost) > 0 ? ` El costo por envío de ${escapeHtml(formatMoney(toCents(order.shippingCost)))} está incluido en Universidad Continental.` : ""}</p>` : ""}${action(link, `Pagar y seguir el pedido ${order.orderNumber}`)}<p style="margin:22px 0 0;font-size:12px;line-height:1.9;color:#666674">La guía de pago está adjunta en PDF. Desde el seguimiento encontrarás las cuentas y podrás adjuntar tus comprobantes. El equipo te avisará cuando avance la atención.</p>`);
}
export function renderOrderUpdate(tracking: EmailOrder, { title, body, link, trackingUrl, createdAt }: { title: string; body: string; link: string; trackingUrl?: string; createdAt: Date }) {
  const stamp = dateFormat.format(createdAt);
  return shell(`<p style="margin:0;color:#6802c1;font-size:10px;font-weight:700;letter-spacing:.7px">Pedido ${escapeHtml(tracking.order.orderNumber)} · ${escapeHtml(stamp)}</p><h1 style="font-size:22px;line-height:1.4;margin:12px 0 0">${escapeHtml(title)}</h1>${action(link, `${title} · Ver pedido ${tracking.order.orderNumber}`)}<p style="font-size:13px;line-height:1.9;margin:0">${escapeHtml(body)}</p>${trackingUrl && /^https:\/\//.test(trackingUrl) ? `<p style="margin:20px 0 0"><a href="${escapeHtml(trackingUrl)}" style="color:#6802c1;font-size:12px;font-weight:600">Consultar este envío con el courier ↗</a></p>` : ""}`);
}
